VGG Implemention in Tensorflow 2.0
yusugomori/deeplearning-tf2 pull request #3
Opened 2019-05-21 12:09 UTC by jeffin07

2019-05-22 04:55 UTC, yusugomori commented
Thank you for your PR! It seems your implementation is using only keras (e.g. not using `tf.GradientTape` but using `model.fit()`), so it would be nice to change the file name to `vgg16_mnist_beginner.py`. Also, it would be grateful to follow the steps implemented in [ResNet](https://github.com/yusugomori/deeplearning-tf2/blob/master/models/resnet34_fashion_mnist_beginner.py) or [LeNet](https://github.com/yusugomori/deeplearning-tf2/blob/master/models/lenet_mnist_beginner.py).

2019-05-22 05:53 UTC, jeffin07 commented
@yusugomori Thanks for the feedback  will update the pull request

2019-05-28 05:19 UTC, yusugomori requested changes
Added some comments. Please see check them and re-push to the repo! Thank you!

2019-05-28 05:19 UTC, yusugomori commented on models/vgg16_mnist_beginner.py
> +		self.conv1_1 = tf.keras.layers.Conv2D(
Import all layers used in the model at the beggining of the code, and write only layer name (`Dense`, `Conv2D`, etc.) in the model.

2019-05-28 05:19 UTC, yusugomori commented on models/vgg16_mnist_beginner.py
> +class Vgg16(tf.keras.Model):
import just `Model`, not `tf.keras.**`

2019-05-28 05:19 UTC, yusugomori commented on models/vgg16_mnist_beginner.py
> +					padding="same", activation="relu")
Use single quote, not double quote (to unify the style).

2019-05-28 05:19 UTC, yusugomori commented on models/vgg16_mnist_beginner.py
> +		# layers needed
Remove comments in the model

2019-05-28 05:19 UTC, yusugomori commented on models/vgg16_mnist_beginner.py
> +		# ops
Please remove comments in the model.

2019-05-28 05:19 UTC, yusugomori commented on models/vgg16_mnist_beginner.py
> +# network.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
Remove comments here.

2019-05-28 05:19 UTC, yusugomori commented on models/vgg16_mnist_beginner.py
> +
Use `if __name__ == '__main__'` so that this file can be imported from other codes.

2019-05-28 05:19 UTC, yusugomori commented on models/vgg16_mnist_beginner.py
> +
Follow the steps implemented in other codes. 
(add 
```
'''
Load data
'''
 etc.)

2019-05-28 05:19 UTC, yusugomori commented on models/vgg16_mnist_beginner.py
> +	with tf.GradientTape(watch_accessed_variables=False) as tape:
This is not how other files implements. Please follow the steps implemented in other codes.

2019-05-28 05:32 UTC, jeffin07 commented
@yusugomori Will update the PR

2019-05-28 07:31 UTC, yusugomori commented
@jeffin07 Thanks for the fixes! I'll finalize the code so could you change the branch from `yusugomori/master` to `yusugomori/vgg16`?
https://github.com/yusugomori/deeplearning-tf2/tree/yusugomori/vgg16

2019-05-28 07:55 UTC, jeffin07 commented
@yusugomori I have changed the base branch. :)

2019-06-13 06:21 UTC, jeffin07 commented
@yusugomori is there any changes to make ?

2019-07-10 09:47 UTC, yusugomori commented
@jeffin07 Sorry for late reply, and thanks for the update!
Will merge into master branch.

2019-07-10 09:47 UTC, merged